### ISSUE TITLE
Any hope of sending CI builds to bintray so people can use them?

### ISSUE THREAD

**Issue by Artoria2e5** [hawaii-desktop/qtaccountsservice#15]
It will look much better if I can use some pre-built versions for Ubuntu 12.04 in sddm/sddm#439
##

**Comment by plfiorini** [comment]
Yes that would be way much better than building qtaccountsservice every time sddm CI runs. Perhaps https://bintray.com could be useful.

**Comment by plfiorini** [comment]
Done
