### ISSUE TITLE
It has the potential to lock up the entire plasma workspace session

### ISSUE THREAD

**Issue by xiangzhai** [hawaii-desktop/qtaccountsservice#9]
I'm a bit concerned by the blocking calls in AccountsService here:
https://github.com/hawaii-desktop/qtaccountsservice/blob/master/src/accountsservice/accountsmanager.cpp#L107

That has the potential to lock up the entire plasma workspace session; which obviously isn't ideal.
Blocking calls are a problem if we can't rely on the remote service /always/ behaving.

**Comment by plfiorini** [comment]
Yep the API needs to be completely async

**Comment by xiangzhai** [comment]
let`s fix it ;P

**Comment by plfiorini** [comment]
Yes, added to the API review task list.

The plan:

0.7.0 is a release which should be as much reliable as we can.
This way issues that can lead to API changes are still allowed until 1.0 but most the most important concerns are already addressed with 0.7.0. With 0.7.0 we can add QtAccountsService as a (still optional) dep on sddm.
